Repository medik8s/poison-pill, pull requests merged in 2021-07, with the labels that each got.

#56 update readme with current situation
  README.md
Labels: approved, lgtm

#57 add timeout for api-server requests when checking if other node is healthy
  pkg/apicheck/check.go
  pkg/peerhealth/server.go
Labels: approved, lgtm

#58 auto generate VERSION based on annotated tag
  Makefile
Labels: approved, lgtm

#54 Push a container image on tag and release
  .github/workflows/post-submit.yaml
Labels: lgtm

#61 [Bug 1975789] fix nodes that rebooted when there was an api-server failure + improved logging
  pkg/apicheck/check.go
  pkg/peers/peers.go
Labels: approved, lgtm

#62 Re-create config CR if it was deleted
  config/rbac/role.yaml
  controllers/poisonpillconfig_controller.go
  main.go
Labels: approved, lgtm

#59 Add e2e test
  Makefile
  e2e/poison_pill_test.go
  e2e/suite_test.go
  e2e/utils/node.go
  e2e/utils/pod.go
  pkg/apicheck/check.go
  pkg/peerhealth/server.go
Labels: approved, lgtm

#60 Fix the container image name in Makefile
  .github/workflows/post-submit.yaml
  .github/workflows/pre-submit.yaml
  Makefile
Labels: approved, lgtm

#64 e2e: wait longer for PP pod (needed after fresh deployment)
  e2e/poison_pill_test.go
Labels: approved, lgtm

#65 Avoid remediation loops by not restoring node's status.
  controllers/poisonpillremediation_controller.go
Labels: approved, lgtm

#66 e2e: check all nodes in the API server issue test case
  e2e/poison_pill_test.go
Labels: approved, lgtm

#69 reduce cpu requirement from 100m to 20m
  bundle.Dockerfile
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  install/poison-pill-deamonset.yaml
Labels: approved, lgtm

#70 Prevent remediation loops by adding remediation cooldown
  controllers/poisonpillremediation_controller.go
Labels: approved, lgtm

#67 Prevent potential peer list mutation
  pkg/peers/peers.go
Labels: approved, lgtm

#77 fix bundle
  bundle/manifests/poison-pill.clusterserviceversion.yaml
Labels: approved

#76 output e2e test log even when tests succeed
  Makefile
Labels: approved, lgtm

#75 [bug 1981402] remediation cooldown is not working
  controllers/controller_test.go
  controllers/poisonpillremediation_controller.go
  e2e/poison_pill_test.go
Labels: approved

#80 auto create poison pill remediation template on boot
  api/v1alpha1/poisonpillconfig_types.go
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/poisonpillremediation_controller.go
  main.go
Labels: approved

#81 Adding an if clause for possible conflict error for r.client .
  controllers/poisonpillremediation_controller.go
Labels: approved, lgtm, ok-to-test

#71 e2e test - wait until all expected logs exist
  e2e/poison_pill_test.go
Labels: approved

#68 Remove unused code
  pkg/peerhealth/client.go
  pkg/peers/peers.go
  pkg/render/render.go
Labels: approved, lgtm

#82 update bundle maintainers to include medik8s name and email
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved

#83 remove releases folder
  releases/0.0.5/manifests/poison-pill-controller-manager-metrics-service_v1_service.yaml
  releases/0.0.5/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml
  releases/0.0.5/manifests/poison-pill-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.0.5/manifests/poison-pill-manager-config_v1_configmap.yaml
  releases/0.0.5/manifests/poison-pill-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.0.5/manifests/poison-pill.clusterserviceversion.yaml
  releases/0.0.5/manifests/poison-pill.medik8s.io_poisonpillconfigs.yaml
  releases/0.0.5/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
  releases/0.0.5/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  releases/0.0.5/metadata/annotations.yaml
  releases/0.0.5/tests/scorecard/config.yaml
  releases/0.0.6/manifests/poison-pill-controller-manager-metrics-service_v1_service.yaml
  releases/0.0.6/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml
  releases/0.0.6/manifests/poison-pill-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.0.6/manifests/poison-pill-manager-config_v1_configmap.yaml
  releases/0.0.6/manifests/poison-pill-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.0.6/manifests/poison-pill.clusterserviceversion.yaml
  releases/0.0.6/manifests/poison-pill.medik8s.io_poisonpillconfigs.yaml
  releases/0.0.6/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
  releases/0.0.6/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  releases/0.0.6/metadata/annotations.yaml
  releases/0.0.6/tests/scorecard/config.yaml
  releases/0.1.0/manifests/poison-pill-controller-manager-metrics-service_v1_service.yaml
  releases/0.1.0/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml
  releases/0.1.0/manifests/poison-pill-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.1.0/manifests/poison-pill-manager-config_v1_configmap.yaml
  releases/0.1.0/manifests/poison-pill-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.1.0/manifests/poison-pill.clusterserviceversion.yaml
  releases/0.1.0/manifests/poison-pill.medik8s.io_poisonpillconfigs.yaml
  releases/0.1.0/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
  releases/0.1.0/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  releases/0.1.0/metadata/annotations.yaml
  releases/0.1.0/tests/scorecard/config.yaml
  releases/0.1.1/manifests/poison-pill-controller-manager-metrics-service_v1_service.yaml
  releases/0.1.1/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml
  releases/0.1.1/manifests/poison-pill-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.1.1/manifests/poison-pill-manager-config_v1_configmap.yaml
  releases/0.1.1/manifests/poison-pill-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  releases/0.1.1/manifests/poison-pill.clusterserviceversion.yaml
  releases/0.1.1/manifests/poison-pill.medik8s.io_poisonpillconfigs.yaml
  releases/0.1.1/manifests/poison-pill.medik8s.io_poisonpillremediations.yaml
  releases/0.1.1/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  releases/0.1.1/metadata/annotations.yaml
  releases/0.1.1/tests/scorecard/config.yaml
Labels: approved, lgtm

#85 Reduce memory footprint
  pkg/apicheck/check.go
  pkg/peers/peers.go
Labels: approved, lgtm

#86 Increase memory allocation
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manager/manager.yaml
  install/poison-pill-deamonset.yaml
Labels: approved

#88 create version 0.1.3
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved
