Repository medik8s/poison-pill, pull requests merged in 2022-02, with the labels that each got.

#111 Remove service account yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#132 Update poison pill owners
  OWNERS
Labels: approved, lgtm

#133 Run unit tests on release branches
  .github/workflows/pre-submit.yaml
Labels: approved, lgtm

#136 Fix poison pill e2e test - updating VolumeAttachment version
  e2e/poison_pill_test.go
Labels: approved, lgtm

#131 Change channel name from alpha to stable
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#142 Fix olm dashboard errors
  api/v1alpha1/poisonpillconfig_types.go
  api/v1alpha1/poisonpillremediation_types.go
  api/v1alpha1/poisonpillremediationtemplate_types.go
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  bundle/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  config/crd/bases/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved, lgtm

#143 Backport fix olm dashboard errors
  api/v1alpha1/poisonpillconfig_types.go
  api/v1alpha1/poisonpillremediation_types.go
  api/v1alpha1/poisonpillremediationtemplate_types.go
  bundle.Dockerfile
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  bundle/manifests/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/poison-pill.medik8s.io_poisonpillremediationtemplates.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved

#145 remove suggestion namespace
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved, lgtm

#148 add support annotation-3
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manifests/bases/poison-pill.clusterserviceversion.yaml
Labels: approved, lgtm

#150 add priorityClassName
  bundle/manifests/poison-pill.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm
